site_name: CS-POGIL
site_url: https://cspogil.github.io/
repo_url: https://github.com/cspogil/cspogil.github.io

extra:
  consent:
    title: Under Construction
    description: >-
      This site is currently being developed, so you may
      find incomplete pages, broken links, typos, etc.

extra_css:
  - tweaks.css?v=2025-07-17

watch:
  - tables

markdown_extensions:

  # https://python-markdown.github.io/extensions/
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - smarty
  - tables
  - toc

  # https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

hooks:
  - hooks/bread.py
  - hooks/home.py
  - hooks/short.py

plugins:
  - search
  - tags
  - awesome-nav

theme:
  name: material
  custom_dir: overrides
  favicon: favicon.ico
  logo: img/light-bulb.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest
